### ISSUE TITLE
Error installing on Ubuntu Xenial

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime-debian-packaging#10]
Error installing on Xenial as well.

apt:
```
$ sudo apt install ./libretime_3.0.0~alpha.8-1ubuntu2_amd64.deb
Reading package lists... Done
E: Unsupported file ./libretime_3.0.0~alpha.8-1ubuntu2_amd64.deb given on commandline
```

dpkg:
```
$ sudo dpkg -i libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb
(Reading database ... 94811 files and directories currently installed.)
Preparing to unpack libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb ...postinst called with unknown argument `install' 
dpkg: error processing archive libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb (--install): subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing: libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb
```

_Originally posted by @alternativesurfer in https://github.com/LibreTime/libretime-debian-packaging/issues/9#issuecomment-540255468_

**Comment by paddatrapper** [comment]
@alternativesurfer what is the checksum of the deb you downloaded and what version of apt do you have?

**Comment by alternativesurfer** [comment]
Hi, sorry, missed that update.
Just tested again on LibreTime 3.0.0~alpha.8-1u3 and receive this error:
```
$ sudo apt install libretime_3.0.0.alpha.8-1ubuntu3_amd64.de                                                                                                                                                                                                                                             b
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb
E: Couldn't find any package by glob 'libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb                                                                                                                                                                                                                                             '
E: Couldn't find any package by regex 'libretime_3.0.0.alpha.8-1ubuntu3_amd64.de                                                                                                                                                                                                                                             b'
```

APT: 1.2.32

Checksums
MD5
eb01c1082e4335f06b39f0b213ca9f31  libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb
SHA1
4ef6cfb0ac37afbb56ba4cb611cc8edeb321b693  libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb
SHA256
d6c58267b96d09f53949bc3c77dd2b05eae1a2b7c7999ec7d63caff06e663a47  libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb

MD5
3ffb6f126589e4fb9cfae5ddfa4ce9b7  libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb
SHA1
d24c732b7a089f6a6a94a676f9ea1a43cbed2b89  libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb
SHA256
87357104c07081f7b876f746e3da633679e4c5aabd14008966aac672e5c838cd  libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb

**Comment by paddatrapper** [comment]
> `$ sudo apt install libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb`

You need to specify a path, otherwise apt will try install it from the repos. Run this instead:

```
sudp apt install ./libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb
```

**Comment by m0ck0** [comment]
having the same issue in bionic, kindof, any hints on what should i check?

`Get:1 /home/ubuntu/libretime/libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb libretime amd64 3.0.0~alpha.8-1ubuntu3 [12.0 MB]
(Reading database ... 103959 files and directories currently installed.)
Preparing to unpack .../libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb ...
postinst called with unknown argument `install'
dpkg: error processing archive /home/ubuntu/libretime/libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb (--unpack):
 new libretime package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /home/ubuntu/libretime/libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
ubuntu@xxx:~/libretime$ apt -v
apt 1.6.12 (amd64)
ubuntu@xxx:~/libretime$ md5sum libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb 
3ffb6f126589e4fb9cfae5ddfa4ce9b7  libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb
ubuntu@xxx:~/libretime$ 
`

**Comment by paddatrapper** [comment]
@m0ck0 what command are you using to install?

**Comment by m0ck0** [comment]
sudo apt install icecast2 ./libretime_3.0.0.alpha.8-1ubuntu3_amd64.deb

**Comment by paddatrapper** [comment]
For some reason dpkg is calling `libretime.postinst` with the install argument, instead of `libretime.preinst`. I have fixed it and it will be in the next release

**Comment by alternativesurfer** [comment]
> 
> anyway i ended up installing it by downloading de tar.gz and runing ./install and worked like a charm.

I ended up going this route however received an error again:

```
Install default Airtime apache configuration? (Y/n): y

-----------------------------------------------------
                * Configuring Apache *
-----------------------------------------------------
AH00526: Syntax error on line 26 of /etc/apache2/sites-enabled/airtime.conf:
Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration
ERROR: unknown location of Apache sites-available or virtual host directory!
```

Seems like the autoinstaller is not enabling rewrite.

**Comment by paddatrapper** [comment]
I suggest you do one of three things:

1. Open an issue at LibreTime/libretime with the details
1. Ask on [Discourse](https://discourse.libretime.org/)
1. Ask on [Mattermost](https://chat.libretime.org)

Where more people will be able to help you
