### ISSUE TITLE
LibreTime on Armbian (ubuntu 18.04 on OragePi PC - 32bit)

### ISSUE THREAD

**Issue by maxlinux2000** [LibreTime/libretime-debian-packaging#11]
Hi
I have successfully installed LibreTime on a small OrangePi PC under Armbian (based on ubuntu 18.04). (OrangePi PC is like a RaspberryPi2)
I have used libretime-debian-packaging fron github, convinced that I would have prepared a .deb to install it in another machine, but I don't understand how the packagin system works.

After launching the ./build.sh script and resolving all the dependencies, I searched for a .deb and did not find it .... so I launched the ./install.sh script and I have installed libretime on the machine test.
It wasn't what I wanted, but anyway libretime works very well it seems to me.

So I can confirm that libretime can be installed under ARM processors with Armbian bionic.

Now some questions:

1. I would like to install libretime under a control panel such as ISPConfig, and have icecast on another server (this is why I want to use the version that I have compiled for me with SSL support)

2. Is it possible to use MySQL / MariaDB instead of PostgreSQL?

3. Ideally, a Wordpress-style installer should be inserted and then the icecast mount point can be indicated on another server.

Regards
MaX

**Comment by Robbt** [comment]
1. You can easily configure LibreTime to connect to another Icecast server under the streaming settings. Currently LibreTime isn't designed to be used on a server hosting other sites, not to say you couldn't do this but ideally Libretime is on its own virtual machine or its own bare metal server because of the amount of different services it relies upon. At the very least it can't be easily set up under a shared hosting environment such as IspConfig w/o having root access to the server.

2. MySQL is not supported as the backend was designed for PostgreSQL and supporting mysql is not a trivial change.

3. Because LibreTime requires the setup of various root level services such as rabbitMQ, and various python based services it couldn't be installed exclusively via the web and will require either a package, docker or a script-based installer such as the one you ran. There is a web-based installer after you run the script-based install and I do agree that we should do something about the Icecast during the web-based install script as the way it is setup currently is not good.

**Comment by OdinVex** [comment]
>     2. MySQL is not supported as the backend was designed for PostgreSQL and supporting mysql is not a trivial change.

Could you elaborate on this? I know this is an old Issue but I'm curious about running MariaDB/MySQL as a backend too.

**Comment by paddatrapper** [comment]
Someone needs to put in the work to implement it and then commit to supporting it. Only supporting PostgreSQL is something we inherited from Airtime

**Comment by OdinVex** [comment]
That doesn't explain it well at all. It's SQL, how does the implementation differ? Just the driving function calls or is there some SQL you use that literally needs something from PSQL?

**Comment by paddatrapper** [comment]
There are a lot of assumptions baked into the code. While Django supports multiple database backends, they are slight differences between them. Same goes for Zend for PHP. It may be a simple change to support both, but it requires someone to put in the work to do so and then commit to help support it afterwards

**Comment by OdinVex** [comment]
That doesn't explain it at all. It's SQL. It is SQL. The only thing that could possibly need changing is the actual functions used, not the SQL unless you've gone out of our way to use vendor-specific SQL stuff. That's what I was asking about, what needs changing. I'd rather write my own radio server at this point. LT was an absolute waste of time trying to get stable in Dockers without relying on ancient version tags and even worse to find so many little issues around the front-end let alone the pain it was to try to stream FLAC. Good luck to the project though.

**Comment by paddatrapper** [comment]
> It's SQL. It is SQL

No it isn't. We don't write direct SQL much. We rely on other libraries to abstract that away. Zend for PHP and Django for Python. Those have some differences between different SQL engines. For examples see the Django docs on their support https://docs.djangoproject.com/en/5.0/ref/databases/

The biggest blocker to supporting multiple database backends is someone willing to do it. All the current maintainers do not have the time or motivation to work on it - we have more pressing issues that we are dealing with, like getting PHP 8 support landed

**Comment by OdinVex** [comment]
Marked as abuse? How insecure is your ego about someone mentioning LT issues?

**Comment by jooola** [comment]
> Marked as abuse? How insecure is your ego about someone mentioning LT issues?

This one is on me, as I was a bit annoyed by the tone you are using. I might have marked it as abuse a bit fast, but I would really prefer to keep the discussion civil, and that we respect the work of others.

**Comment by OdinVex** [comment]
> This one is on me, as I was a bit annoyed by the tone you are using. I might have marked it as abuse a bit fast, but I would really prefer to keep the discussion civil, and that we respect the work of others.

Before there was no tone and nothing wrong with what I said and I do respect the work of others, it was genuine and civil (edit: all responses until that mark as abuse). As for the tone of my **reply** being uncivil, that action (edit: the marking as abuse) looked like an ego response from them. Seeing as it wasn't, I do apologize.
