### ISSUE TITLE
ERROR: Distribution "Debian GNU/Linux 11 (bullseye)" is not supported with "debian-11"!

### ISSUE THREAD

**Issue by Wots-g** [LibreTime/libretime-debian-packaging#17]
root@Server:# git clone https://github.com/LibreTime/libretime-debian-packagi ng.git
Клонирование в «libretime-debian-packaging»…
remote: Enumerating objects: 166375, done.
remote: Counting objects: 100% (727/727), done.
remote: Compressing objects: 100% (596/596), done.
remote: Total 166375 (delta 89), reused 505 (delta 65), pack-reused 165648
Получение объектов: 100% (166375/166375), 387.06 MiB | 209.00 KiB/s, готово.
Определение изменений: 100% (116435/116435), готово.
Updating files: 100% (5861/5861), готово.
root@Server-R:# cd
root@Server-R:# cd libretime-debian-packaging
root@Server-R:/libretime-debian-packaging# ./install

Detecting distribution and release ...
Detected distribution id: debian
Detected distribution release id: 11
Detected distribution description: Debian GNU/Linux 11 (bullseye)
ERROR: Distribution "Debian GNU/Linux 11 (bullseye)" is not supported with "debian-11"!

#################

Host Debian Bullseye 11. 1

????

**Comment by paddatrapper** [comment]
Debian 11 support requires a new libretime release to be packaged here. Until then, you can install from https://github.com/LibreTime/libretime using the install script
