### ISSUE TITLE
Zendframework issue

### ISSUE THREAD

**Issue by whiteblue3** [LibreTime/libretime-debian-packaging#5]
I have some error

PHP Fatal error:  Declaration of Zend_Rest_Route::assemble($data = Array, $reset = false, $encode = true) must be compatible with Zend_Controller_Router_Route_Module::assemble($data = Array, $reset = false, $encode = true, $partial = false) in /srv/airtime/vendor/zendframework/zendframework1/library/Zend/Rest/Route.php on line 52

cannot avoid this error.
can you help?

**Comment by hairmare** [comment]
This will be fixed in the next LibreTime release. For now you need to use a php < 7.2.

**Comment by paddatrapper** [comment]
Unfortunately the deb only works with Ubuntu Xenial (16.04) as 18.04 and Debian Buster ship php >= 7.2. Once the php 7.2 compat PR is merged, we will be able to extend the supported versions for the deb

**Comment by whiteblue3** [comment]
thank you guys
