### ISSUE TITLE
Ubuntu Bionic Deb file ?

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime-debian-packaging#6]
Hey @paddatrapper I saw we have Debian Stretch and Ubuntu Xenial debian packages for the latest alpha.7 release and I was just curious if you were planning one for 18.04 - since it is LTS for 10 years it might be the best option.

**Comment by paddatrapper** [comment]
I definitely plan on it. I want to create for Bionic and Buster, but I just haven't had a chance yet. Hopefully I'll be able to work on it next week or the week after

**Comment by Robbt** [comment]
Great I was just curious.

**Comment by paddatrapper** [comment]
alpha.8 now has a package compatible with Ubuntu Bionic and Xenial
