### ISSUE TITLE
Debian install fails on Ubuntu Bionic - asking for php7.0 but  Bionic is 7.2

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime-debian-packaging#9]
Fresh Bionic install. Clue at the bottom.

`
Using apt:
apt install icecast2 ./libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb
Reading package lists... Done
E: Unsupported file ./libretime_3.0.0~alpha.8-1ubuntu2_amd64.deb given on commandline

Using dpkg:
dpkg -i libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb
Selecting previously unselected package libretime.
(Reading database ... 87072 files and directories currently installed.)
Preparing to unpack libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb ...
postinst called with unknown argument `install'
dpkg: error processing archive libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb (--install):
 new libretime package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb

Using GDebi:
gdebi libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
**This package is uninstallable
Dependency is not satisfiable: libapache2-mod-php7.0**
`

**Comment by alternativesurfer** [comment]
Error installing on Xenial as well.

apt:
~$ sudo apt install ./libretime_3.0.0~alpha.8-1ubuntu2_amd64.deb
Reading package lists... Done
E: Unsupported file ./libretime_3.0.0~alpha.8-1ubuntu2_amd64.deb given on commandline

dpkg:
$ sudo dpkg -i libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb
(Reading database ... 94811 files and directories currently installed.)
Preparing to unpack libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb ...postinst called with unknown argument `install' 
dpkg: error processing archive libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb (--install): subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing: libretime_3.0.0.alpha.8-1ubuntu2_amd64.deb

**Comment by paddatrapper** [comment]
@alternativesurfer that is a different issue... I have opened #10 to track it
